blank_issues_enabled: false
contact_links:
    - name: 🌟 new Script request
      url: https://github.com/vcano5/ProxmoxVE/discussions/new?category=request-script
      about: For feature/script requests, please use the Discussions section.
    - name: 🤔 Questions and Help
      url: https://github.com/vcano5/ProxmoxVE/discussions
      about: For suggestions or questions, please use the Discussions section.
    - name: 💻 Discord
      url: https://discord.gg/jsYVk5JBxq
      about: Join our Discord server to chat with other users in the Proxmox Helper Scripts community.
